#!/bin/bash -l

set -e
perl --version
PATH=$PATH:/home/smoker/.rakudobrew/bin
rakudobrew build moar
rakudobrew switch moar-HEAD
rakudobrew build-panda
cd ~/emmentaler
curl -O http://feather.perl6.nl:3000/projects.json
./smoker projects.json
mv results.json ~/smoke-history/results-$(date +%Y%m%d).json
cd ..
scp ~/smoke-history/results-$(date +%Y%m%d).json smoke.perl6.org@smoke.perl6.org:smoke-history/
tools/perl6-ecosystem-authors/bin/ecosystem-authors >~/smoke-history/authors
scp ~/smoke-history/authors smoke.perl6.org@smoke.perl6.org:smoke-history/
